import com.mesosphere.sbt.BuildPlugin

val projectScalaVersion = "2.10.6"
val projectVersion = "0.1.0-SNAPSHOT"

lazy val root = project.in(file("."))
  .settings(
    name := "sbt-dcos",
    version := projectVersion,
    organization := "com.mesosphere",
    scalaVersion := projectScalaVersion,
    sbtPlugin := true
  )
  .settings(
    // Decode the transitive plugin module IDs from the BuildInfo generated by the metabuild
    metabuild.BuildInfo.pluginModuleInfo.map { case (organization, (name, revision)) =>
      addSbtPlugin(organization % name % revision)
    }
  )
  .settings(BuildPlugin.publishSettings)
  .settings(
    pomExtra :=
      <url>https://dcos.io</url>
      <licenses>
        <license>
          <name>Apache License Version 2.0</name>
          <url>https://github.com/dcos/sbt-dcos/blob/master/LICENSE</url>
          <distribution>repo</distribution>
        </license>
      </licenses>
      <scm>
        <url>https://github.com/dcos/sbt-dcos.git</url>
        <connection>scm:git:https://github.com/dcos/sbt-dcos.git</connection>
      </scm>
      <developers>
        <developer>
          <name>Charles Ruhland</name>
        </developer>
        <developer>
          <name>Jesus Larios Murillo</name>
        </developer>
        <developer>
          <name>José Armando García Sancio</name>
        </developer>
      </developers>
  )
